name: graphql_2_rest
description: A simple way to convert GraphQL queries to REST in order to use any HTTP client for performing a request.
version: 1.0.2
homepage: https://github.com/phimary/graphql_2_rest

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
